#!/usr/bin/env bash
source $(dirname $(dirname $0))/lib/utils.sh

bin="rustup"
plugin="rust"
revision=$(get_preset_version_for $plugin)
prefix=$(get_install_path $plugin "version" $revision)
asdf_exec=$(asdf_dir)"/bin/private/asdf-exec"

if [ $# -eq 0 ]; then
  exec $asdf_exec $plugin $bin "$@" --help
else
  exec $asdf_exec $plugin $bin "$@" --disable-sudo --prefix=$prefix
fi
